name: DevSecOps CI/CD

on:
  push:
    branches: [main]
  pull_request:

jobs:
  devsecops:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Instalacja zależności i narzędzi
      - name: Install dependencies and tools
        run: |
          npm install
          npm install -g nyc
          npm install -g cypress
          npm install -g mocha ts-node source-map-support

      # SCA - npm audit
      - name: Run SCA (npm audit)
        run: npm audit --audit-level=high

      # SAST - Semgrep
      - name: Run Semgrep SAST
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/default"

      # Secrets Scan - GitLeaks
      - name: Scan for secrets with GitLeaks
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: ""
          args: "--verbose"

      # Build Docker image
      - name: Build Docker image
        run: docker build -t juice-shop:latest .

      # Trivy scan of Docker image
      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: juice-shop:latest
          severity: HIGH,CRITICAL
          format: table

      # Tymczasowe uruchomienie aplikacji do DAST
      - name: Start Juice Shop in Docker
        run: |
          docker run -d -p 3000:3000 --name juice-shop juice-shop:latest
          sleep 15

      # DAST - OWASP ZAP scan
      - name: Run OWASP ZAP DAST scan
        run: |
          docker run --network="host" owasp/zap2docker-stable zap-baseline.py \
            -t http://localhost:3000 \
            -r zap-report.html || true

      # Upload ZAP report
      - name: Upload ZAP report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap-report.html

      # Login to Docker Hub
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Push Docker image to Docker Hub
      - name: Tag and Push Docker image
        run: |
          docker tag juice-shop:latest ${{ secrets.DOCKER_USERNAME }}/juice-shop:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/juice-shop:latest
